name: Auto Merge PRs

on:
  schedule:
    - cron: '0 7 * * *'  # 매일 오전 7시 실행 (UTC 기준)
  workflow_dispatch:  # 수동 실행 가능

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get merge count and PR list
        id: fetch-prs
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const MAX_DAILY_MERGES = 1;
            const today = new Date();

            // `MergeReady` 라벨이 있는 PR 목록 조회
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open",
              per_page: 50
            });

            const mergeReadyPRs = prs.filter(pr =>
              pr.labels.some(label => label.name === "MergeReady")
            ).sort((a, b) => new Date(a.created_at) - new Date(b.created_at));

            if (mergeReadyPRs.length === 0) {
              console.log("No MergeReady PRs found.");
              return;
            }

            // PR 개수에 따라 MAX_WEEKLY_MERGES 설정
            let MAX_WEEKLY_MERGES = 1;
            if (mergeReadyPRs.length > 10) MAX_WEEKLY_MERGES = 2;
            if (mergeReadyPRs.length > 20) MAX_WEEKLY_MERGES = 3;
            if (mergeReadyPRs.length > 30) MAX_WEEKLY_MERGES = 4;

            // 지난 7일간 merge 된 PR 개수 확인
            const { data: mergedPRs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "closed",
              per_page: 50
            });
            
            const last7DaysMerges = mergedPRs.filter(pr => 
              pr.merged_at && new Date(pr.merged_at) >= new Date(today - 7 * 24 * 60 * 60 * 1000) &&
              pr.labels.some(label => label.name === "MergeReady")
            ).length;

            if (last7DaysMerges >= MAX_WEEKLY_MERGES) {
              console.log(`Weekly merge limit reached (${last7DaysMerges}/${MAX_WEEKLY_MERGES}).`);
              return;
            }

            // 가장 오래된 PR 선택
            const selectedPR = mergeReadyPRs[0];
            console.log(`Selected PR: #${selectedPR.number}`);

            core.setOutput("pr_number", selectedPR.number);

      - name: Merge selected PR
        if: steps.fetch-prs.outputs.pr_number != ''
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.fetch-prs.outputs.pr_number }}
          merge-method: squash
